module.exports = [
    "apple",
    "monitor",
    "ipad",
    "macbook",
    "bottle",
    "paperwhite",
    "calculator",
    "body spray",
    "flask",
    "wallet",
    "pen",
    "note 8",
    "samsung",
    "note 7",
    "headphone",
    "watch",
    "earphone",
    "guitar",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "pencil",
    "trimmer",
    "bag",
    "powerbank",
    "beauty products",
    "keyboard",
    "mouse",
    "cable",
    "printer",
    "mobile",
    "perfume",
    "smart watch",
    "galaxy",
    "frontier",
    "ac",
    "freeze",
    "laptop",
    "HP",
    "acer",
    "bass",
    "brass",
    "strings",
    "dj",
    "music",
    "microphones",
    "drums",
    "b&o",
    "echo",
    "fire",
    "fire 7",
    "fire 8",
    "fire 10",
    "fire 7 kids",
    "fire tv",
    "fire tv stick",
    "voyage",
    "oasis",
    "pet",
    "dog",
    "dog food",
    "fish",
    "aquatic pets",
    "birds",
    "smart home",
    "kitchen",
    "bath",
    "lapm",
    "home",
    "event",
    "arts",
    "fine art",
    "lighting",
    "mattress",
    "garden",
    "outdoor",
    "bed",
    "decor",
    "shop",
    "amazon home",
    "software",
    "computer",
    "computer parts",
    "gaming keyboard",
    "mechanical keyboard",
    "drives",
    "storage",
    "ink",
    "toner",
    "office",
    "muscial",
    "bluetooth",
    "bluetooth headphone",
    "car electronics",
    "video games",
    "tv",
    "camera",
    "home audio",
    "dslr",
    "mirrorless camera",
    "blu ray",
    "salon",
    "spa",
    "vitamins",
    "household",
    "health",
    "sports",
    "dress",
    "jacket",
    "pant",
    "jeans",
    "alcohol",
    "toys",
    "games",
    "women",
    "men",
    "girls",
    "boys",
    "shoes",
    "luggage",
    "baby",
    "handmade",
    "jewelary",
    "gold",
    "diamond",
    "iphone se",
    "iphone 6",
    "iphone 6s",
    "note 9",
    "nokia",
    "motorola",
    "golf",
    "gym",
    "cycling",
    "clothing",
    "scooters",
    "water sports",
    "skates",
    "skateboards",
    "winter sports",
    "climbing",
    "gadgets",
    "house",
    "body",
    "food",
    "electrical",
    "light",
    "switch",
    "10$",
    "automative",
    "car",
    "vehicle",
    "tires",
    "wheels",
    "motorcycle",
    "powerstrap",
    "mirror",
    "knob",
    "lock",
    "rogue",
    "playstation",
    "xbox",
    "denim",
    "fossil",
    "plus size",
    "romantic",
    "glam",
    "causal",
    "sporty",
    "boho",
    "edgy",
    "sandles",
    "bags",
    "skirts",
    "pointed toe",
    "pumps",
    "full flat",
    "collar",
    "neclace",
    "silk",
    "teen",
    "workout",
    "accessories",
    "hat",
    "sunglass",
    "work",
    "weekday",
    "hoodie",
    "fall chinos",
    "sneakers",
    "belt",
    "athletic shows",
    "leather",
    "loafer",
    "oxfords",
    "adidas",
    "nike",
    "back to school"
]